#!/bin/bash -ue

# Check the commandline argument
if (( "$#" != 1 )); then
    echo "usage: $0 [number of path variables] > [OUTPUT_FILENAME]"
    exit 0
fi

# Generate the header
cat <<EOF
(* -*- mode: imitator-property; -*- *)
(************************************************************
 *                 HyPTCTLChecker PROPERTY
 *
 *
 * Description     : Toy example to evaluate the scalability of EFSynth with respect to the number of quantified path variables.
 * Assumptions     : The model should have a parameter "parameter"
 * Source          : Own work
 * Author          : Étienne André, Masaki Waga
 * License         : Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
 *
 * This file is automatically generated.
 *
 * HyPTCTLChecker version: alpha
 * IMITATOR version: 3.4-alpha
 ************************************************************)
(* We use the special clock variable for the global time *)
use global_time;
<*
property := #synth EF_[param,param] (
	(* Assert the number of sugars *)
EOF

# Generate the main body
for i in $(seq "$1"); do
    printf "	COUNT_SUGAR_%d - COUNT_SUGAR_%d = 1" "$i" "$((i+1))"
    if ((i < $1)); then
        printf " &&"
    fi
    printf "\n"
done

# Generate the footer
cat <<EOF
	)
;
*>
EOF
